exclude: ['*.md', 'CNAME', '.customPath', '*.code-workspace', 'Gemfile', 'Gemfile.lock', '.bundle/*.*', '.jekyll-cache/*.*', 'true']
gems:
  - jekyll-auto-image
  - jekyll-sitemap

nname: "L Y N N"
aname: "Lynn H."
imgchar: "/images/photographie"
lifeinvader: "#"
